version: '3'

volumes:
  pg_data:
  pgadmin_data:
  redis_data:
  static:
  media:

services:
  db_postgres:
    container_name: db_payment
    image: postgres:14-alpine
    env_file: .env
    volumes:
      - ./postgres/init_db:/docker-entrypoint-initdb.d
      - pg_data:/var/lib/postgresql/data
    ports:
      - "35432:5432"
    restart: always


  pgadmin:
    container_name: pgadmin_container_payment
    image: dpage/pgadmin4
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD

    depends_on:
      - db_postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G

  redis:
    container_name: redis_payment
    image: redis:latest
    command: redis-server --save 20 1 --loglevel warning
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis/etc/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data

  backend:
    build: ./backend_payment
    restart: always
    env_file: .env
    depends_on:
      - db_postgres
      - celery
    volumes:
      - static:/app/collected_static/
      - media:/app/media/
      - ./logs/backend_payment:/app/logs
    entrypoint: bash /app/entrypoint.sh


  celery:
    container_name: celery
    build: ./backend_payment
    restart: always
    command: celery -A backend_payment.celery:app worker -l warning -n myworker --concurrency=4 --logfile=logs/celery.log
    volumes:
      - media:/app/media/
      - ./logs/celery:/app/logs
    env_file: .env
    depends_on:
      - redis

  celery-beat:
    build: ./backend_payment
    command: celery -A backend_payment.celery:app beat -l info -S django
    env_file: .env
    depends_on:
      - celery


  nginx:
    image: nginx:1.19.3
    env_file: .env
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - ./nginx_dev.conf:/etc/nginx/conf.d/default.conf:ro
      - static:/app/static
      - media:/app/media
